### ISSUE TITLE
Fallback if image is NULL

### ISSUE THREAD

**Issue by AlexandreKilian** [Bukashk0zzz/LiipImagineSerializationBundle#15]
Hello,

Using this Bundle to serialize Vich-Uploads for profile images, i have this Problem:

I want to have a fallback if the user hasnt uploaded an image yet. I tried using the getter to override the image with a default. Unfortunately, if the property is null, the getter isn't being called, so that doesn't seem to work... Is there a way with this bundle to do this, or do I have to find another solution?

**Comment by Bukashk0zzz** [comment]
Hi, 

You can use UrlNormalizer event for this https://github.com/Bukashk0zzz/LiipImagineSerializationBundle#events


Something like this:
```php
public function normalizeFiltered(UrlNormalizerEvent $event)
    {
        if ($event->getUrl() === '') {
            $event->setUrl('http://example.com/default.png');
        }
    }
```

**Comment by AlexandreKilian** [comment]
Unfortunately, this doesnt seem to work... if I just add an empty string into the DB, neither LiipImagineSerializationEventSubscriber nor a custom UrlNormalizer seem to do anything, it just returns the empty string instead of the array with the mappings and original...
I'm Using Vich, JMS Serializer and FOSRestBundle...
I'm really desperate, I've tried so many different things, but as soon as it's not a valid file, it doesnt go through any of the listeners, getters or normalizers

**Comment by Bukashk0zzz** [comment]
Thats ugly but maybe made check in getter of your entity? 
```php
    public function getImage()
    {

       if ($this->image === '') {
            return 'http://example.com/default.png';
        }
        return $this->image;
    }
```
