### ISSUE TITLE
Installation on Symfony 5 failed 

### ISSUE THREAD

**Issue by gilsondelrei** [Bukashk0zzz/LiipImagineSerializationBundle#19]
i tried to install the package on symfony 5 but the **composer** returned with following error:

  **Problem 1**
   ` - bukashk0zzz/liip-imagine-serialization-bundle v2.0.2 requires symfony/dependency-injection ^3.3|^4.0 -> no matching package found.
    - bukashk0zzz/liip-imagine-serialization-bundle v2.0.1 requires symfony/dependency-injection ^3.3 -> no matching package found.
    - bukashk0zzz/liip-imagine-serialization-bundle v2.0.0 requires symfony/dependency-injection ^3.3 -> no matching package found.
    - Installation request for bukashk0zzz/liip-imagine-serialization-bundle ^2.0 -> satisfiable by bukashk0zzz/liip-imagine-serialization-bundle[v2.0.0, v2.0.1, v2.0.2].`

Is it a compatibility problem ? Any chance to upgrade it to Symfony >=4.x and <=5.x ?

thanks in advance

**Comment by Bukashk0zzz** [comment]
Hi, I will try to update bundle

**Comment by Bukashk0zzz** [comment]
Created https://github.com/Bukashk0zzz/LiipImagineSerializationBundle/releases/tag/v3.0.0
