### ISSUE TITLE
PsrCachedReader instead of CachedReader

### ISSUE THREAD

**Issue by NOaMTL** [Bukashk0zzz/LiipImagineSerializationBundle#23]
Hello, I am using Symfony 5.3.7 / Liip 2.6.1 and vich 1.18.0
I have this error.

`Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsSerializeListenerAbstract::__construct(): Argument #2 ($annotationReader) must be of type Doctrine\Common\Annotations\CachedReader, Doctrine\Common\Annotations\PsrCachedReader given, called in C:\ALTIS\symfony\tcb\var\cache\dev\ContainerO8Em8hz\getBukashk0zzzLiipImaginePreSerialization_ListenerService.php on line 23`
(I am using th latest version of this package and i tried to clear cache)

**Comment by jsor** [comment]
I've got the same error. Filed #24 to fix this.

**Comment by Bukashk0zzz** [comment]
Fixed in https://github.com/Bukashk0zzz/LiipImagineSerializationBundle/releases/tag/v3.1.1
