### ISSUE TITLE
Warning: ltrim() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by razvanmitre** [Bukashk0zzz/LiipImagineSerializationBundle#9]
Hello,

I have an issue when I want to serialize an object with this structure:

```
[
    {
      "id": 7,
      "user": {
        "profile_picture": {
          "versions": {
            "original": "57a8c72b249b0_jdfhjd.png",
            "home_thumbnail_large": "http://localhost:8000/media/cache/resolve/home_thumbnail_large/57a8c72b249b0_jdfhjd.png",
            "home_thumbnail_medium": "http://localhost:8000/media/cache/resolve/home_thumbnail_medium/57a8c72b249b0_jdfhjd.png",
            "home_thumbnail_small": "http://localhost:8000/media/cache/resolve/home_thumbnail_small/57a8c72b249b0_jdfhjd.png"
          },
          "id": 2
        }
      },
      "created_at": "2016-08-15T20:26:46+0300"
    }
]
```

So, an array which contains an object which has an user, which has a picture, with multiple filters applied to it. This problem always appears when the picture is not on the root element.

From what I found, the $value parameter received by Bukashk0zzz/lLiipImagineSerializationBundle/EventListener/JmsSerializeListenerAbstract::serializeValue (at line 100) is an array. In fact it is this array:

```
array(4) {
  ["original"]=>
  string(24) "57a8c72b249b0_jdfhjd.png"
  ["home_thumbnail_large"]=>
  string(87) "http://localhost:8000/media/cache/resolve/home_thumbnail_large/57a8c72b249b0_jdfhjd.png"
  ["home_thumbnail_medium"]=>
  string(88) "http://localhost:8000/media/cache/resolve/home_thumbnail_medium/57a8c72b249b0_jdfhjd.png"
  ["home_thumbnail_small"]=>
  string(87) "http://localhost:8000/media/cache/resolve/home_thumbnail_small/57a8c72b249b0_jdfhjd.png"
}
```

The above array should be the final result, is is like it tries to serialize the object multiple times, and the second time it tries it failes because $value is already an array. 

So as a quick fix I extended \Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsPreSerializeListener with:

```
namespace NC\AdminBundle\EventListener;

use Bukashk0zzz\LiipImagineSerializationBundle\Annotation\LiipImagineSerializableField;

class JmsPreSerializeListener extends \Bukashk0zzz\LiipImagineSerializationBundle\EventListener\JmsPreSerializeListener
{
    protected function serializeValue(LiipImagineSerializableField $liipAnnotation, $object, $value)
    {
        if(is_array($value))
            return $value;

        return parent::serializeValue($liipAnnotation, $object, $value);
    }
}
```

And I registered this new listener by adding this in config.yml:

```
bukashk0zzz_liip_imagine_pre_serialization.listener.class: NC\AdminBundle\EventListener\JmsPreSerializeListener
```

But this is a terrible hack. I couldn't find out why it is being serialized multiple times.

Also, I tried calling $object->getFilename() in this method, and it also returns the above array. Already serialized.

Does anyone have any idea why? Or what could be a good solution?

**Comment by Bukashk0zzz** [comment]
JMSserializer often serialize same object 2 times. There a lot of issues about that. 
I add check is value is array or no. So now all must work correct and you don't need your own listener.
